package model.mwgl.vo;

import model.mwgl.eo.AddressUsagesEOImpl;
import model.mwgl.eo.AddressesEOImpl;

import model.mwgl.vo.common.AddressAndUsageVORow;

import oracle.jbo.AttributeList;
import oracle.jbo.JboException;
import oracle.jbo.RowCreateException;
import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 30 05:55:12 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AddressAndUsageVORowImpl extends ViewRowImpl implements AddressAndUsageVORow {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        AddressId {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getAddressId();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setAddressId((Number)value);
            }
        }
        ,
        AddressUsagesId {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getAddressUsagesId();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setAddressUsagesId((DBSequence)value);
            }
        }
        ,
        AssociatedOwnerId {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getAssociatedOwnerId();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setAssociatedOwnerId((Number)value);
            }
        }
        ,
        CreatedBy {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        ExpiredFlag {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getExpiredFlag();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setExpiredFlag((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        ObjectVersionId {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getObjectVersionId();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setObjectVersionId((Number)value);
            }
        }
        ,
        OwnerTypeCode {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getOwnerTypeCode();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setOwnerTypeCode((String)value);
            }
        }
        ,
        UsageTypeCode {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getUsageTypeCode();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setUsageTypeCode((String)value);
            }
        }
        ,
        Address1 {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getAddress1();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setAddress1((String)value);
            }
        }
        ,
        Address2 {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getAddress2();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setAddress2((String)value);
            }
        }
        ,
        AddressId1 {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getAddressId1();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setAddressId1((DBSequence)value);
            }
        }
        ,
        City {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getCity();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setCity((String)value);
            }
        }
        ,
        CountryId {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getCountryId();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setCountryId((String)value);
            }
        }
        ,
        CreatedBy1 {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getCreatedBy1();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setCreatedBy1((String)value);
            }
        }
        ,
        CreationDate1 {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getCreationDate1();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setCreationDate1((Date)value);
            }
        }
        ,
        LastUpdateDate1 {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getLastUpdateDate1();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setLastUpdateDate1((Date)value);
            }
        }
        ,
        LastUpdatedBy1 {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getLastUpdatedBy1();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setLastUpdatedBy1((String)value);
            }
        }
        ,
        Latitude {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getLatitude();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setLatitude((Number)value);
            }
        }
        ,
        Longitude {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getLongitude();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setLongitude((Number)value);
            }
        }
        ,
        ObjectVersionId1 {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getObjectVersionId1();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setObjectVersionId1((Number)value);
            }
        }
        ,
        PostalCode {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getPostalCode();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setPostalCode((String)value);
            }
        }
        ,
        StateProvince {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getStateProvince();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setStateProvince((String)value);
            }
        }
        ,
        CountryName {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getCountryName();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setCountryName((String)value);
            }
        }
        ,
        CreatedBy2 {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getCreatedBy2();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setCreatedBy2((String)value);
            }
        }
        ,
        CreationDate2 {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getCreationDate2();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setCreationDate2((Date)value);
            }
        }
        ,
        IsoCountryCode {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getIsoCountryCode();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setIsoCountryCode((String)value);
            }
        }
        ,
        Language {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getLanguage();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setLanguage((String)value);
            }
        }
        ,
        LastUpdateDate2 {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getLastUpdateDate2();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setLastUpdateDate2((Date)value);
            }
        }
        ,
        LastUpdatedBy2 {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getLastUpdatedBy2();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setLastUpdatedBy2((String)value);
            }
        }
        ,
        ObjectVersionId2 {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getObjectVersionId2();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setObjectVersionId2((Number)value);
            }
        }
        ,
        SourceLang {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getSourceLang();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setSourceLang((String)value);
            }
        }
        ,
        CreatedBy3 {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getCreatedBy3();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setCreatedBy3((String)value);
            }
        }
        ,
        CreationDate3 {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getCreationDate3();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setCreationDate3((Date)value);
            }
        }
        ,
        Description {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getDescription();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        Language1 {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getLanguage1();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setLanguage1((String)value);
            }
        }
        ,
        LastUpdateDate3 {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getLastUpdateDate3();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setLastUpdateDate3((Date)value);
            }
        }
        ,
        LastUpdatedBy3 {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getLastUpdatedBy3();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setLastUpdatedBy3((String)value);
            }
        }
        ,
        LookupCode {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getLookupCode();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setLookupCode((String)value);
            }
        }
        ,
        LookupType {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getLookupType();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setLookupType((String)value);
            }
        }
        ,
        Meaning {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getMeaning();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setMeaning((String)value);
            }
        }
        ,
        ObjectVersionId3 {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getObjectVersionId3();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setObjectVersionId3((Number)value);
            }
        }
        ,
        SourceLang1 {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getSourceLang1();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setSourceLang1((String)value);
            }
        }
        ,
        AddressLabel {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getAddressLabel();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setAddressLabel((String)value);
            }
        }
        ,
        LookupCodeSUsageType {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getLookupCodeSUsageType();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CountriesVO1 {
            public Object get(AddressAndUsageVORowImpl obj) {
                return obj.getCountriesVO1();
            }

            public void put(AddressAndUsageVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(AddressAndUsageVORowImpl object);

        public abstract void put(AddressAndUsageVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int ADDRESSID = AttributesEnum.AddressId.index();
    public static final int ADDRESSUSAGESID = AttributesEnum.AddressUsagesId.index();
    public static final int ASSOCIATEDOWNERID = AttributesEnum.AssociatedOwnerId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int EXPIREDFLAG = AttributesEnum.ExpiredFlag.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int OBJECTVERSIONID = AttributesEnum.ObjectVersionId.index();
    public static final int OWNERTYPECODE = AttributesEnum.OwnerTypeCode.index();
    public static final int USAGETYPECODE = AttributesEnum.UsageTypeCode.index();
    public static final int ADDRESS1 = AttributesEnum.Address1.index();
    public static final int ADDRESS2 = AttributesEnum.Address2.index();
    public static final int ADDRESSID1 = AttributesEnum.AddressId1.index();
    public static final int CITY = AttributesEnum.City.index();
    public static final int COUNTRYID = AttributesEnum.CountryId.index();
    public static final int CREATEDBY1 = AttributesEnum.CreatedBy1.index();
    public static final int CREATIONDATE1 = AttributesEnum.CreationDate1.index();
    public static final int LASTUPDATEDATE1 = AttributesEnum.LastUpdateDate1.index();
    public static final int LASTUPDATEDBY1 = AttributesEnum.LastUpdatedBy1.index();
    public static final int LATITUDE = AttributesEnum.Latitude.index();
    public static final int LONGITUDE = AttributesEnum.Longitude.index();
    public static final int OBJECTVERSIONID1 = AttributesEnum.ObjectVersionId1.index();
    public static final int POSTALCODE = AttributesEnum.PostalCode.index();
    public static final int STATEPROVINCE = AttributesEnum.StateProvince.index();
    public static final int COUNTRYNAME = AttributesEnum.CountryName.index();
    public static final int CREATEDBY2 = AttributesEnum.CreatedBy2.index();
    public static final int CREATIONDATE2 = AttributesEnum.CreationDate2.index();
    public static final int ISOCOUNTRYCODE = AttributesEnum.IsoCountryCode.index();
    public static final int LANGUAGE = AttributesEnum.Language.index();
    public static final int LASTUPDATEDATE2 = AttributesEnum.LastUpdateDate2.index();
    public static final int LASTUPDATEDBY2 = AttributesEnum.LastUpdatedBy2.index();
    public static final int OBJECTVERSIONID2 = AttributesEnum.ObjectVersionId2.index();
    public static final int SOURCELANG = AttributesEnum.SourceLang.index();
    public static final int CREATEDBY3 = AttributesEnum.CreatedBy3.index();
    public static final int CREATIONDATE3 = AttributesEnum.CreationDate3.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int LANGUAGE1 = AttributesEnum.Language1.index();
    public static final int LASTUPDATEDATE3 = AttributesEnum.LastUpdateDate3.index();
    public static final int LASTUPDATEDBY3 = AttributesEnum.LastUpdatedBy3.index();
    public static final int LOOKUPCODE = AttributesEnum.LookupCode.index();
    public static final int LOOKUPTYPE = AttributesEnum.LookupType.index();
    public static final int MEANING = AttributesEnum.Meaning.index();
    public static final int OBJECTVERSIONID3 = AttributesEnum.ObjectVersionId3.index();
    public static final int SOURCELANG1 = AttributesEnum.SourceLang1.index();
    public static final int ADDRESSLABEL = AttributesEnum.AddressLabel.index();
    public static final int LOOKUPCODESUSAGETYPE = AttributesEnum.LookupCodeSUsageType.index();
    public static final int COUNTRIESVO1 = AttributesEnum.CountriesVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AddressAndUsageVORowImpl() {
    }

    /**
     * Gets AddressUsagesEO entity object.
     * @return the AddressUsagesEO
     */
    public AddressUsagesEOImpl getAddressUsagesEO() {
        return (AddressUsagesEOImpl)getEntity(0);
    }

    /**
     * Gets AddressesEO entity object.
     * @return the AddressesEO
     */
    public AddressesEOImpl getAddressesEO() {
        return (AddressesEOImpl)getEntity(1);
    }

    /**
     * Gets CountryCodesEO entity object.
     * @return the CountryCodesEO
     */
    public EntityImpl getCountryCodesEO() {
        return (EntityImpl)getEntity(2);
    }

    /**
     * Gets LookupCodesEO entity object.
     * @return the LookupCodesEO
     */
    public EntityImpl getLookupCodesEO() {
        return (EntityImpl)getEntity(3);
    }

    /**
     * Gets the attribute value for ADDRESS_ID using the alias name AddressId.
     * @return the ADDRESS_ID
     */
    public Number getAddressId() {
        return (Number) getAttributeInternal(ADDRESSID);
    }

    /**
     * Sets <code>value</code> as attribute value for ADDRESS_ID using the alias name AddressId.
     * @param value value to set the ADDRESS_ID
     */
    public void setAddressId(Number value) {
        setAttributeInternal(ADDRESSID, value);
    }

    /**
     * Gets the attribute value for ADDRESS_USAGES_ID using the alias name AddressUsagesId.
     * @return the ADDRESS_USAGES_ID
     */
    public DBSequence getAddressUsagesId() {
        return (DBSequence)getAttributeInternal(ADDRESSUSAGESID);
    }

    /**
     * Sets <code>value</code> as attribute value for ADDRESS_USAGES_ID using the alias name AddressUsagesId.
     * @param value value to set the ADDRESS_USAGES_ID
     */
    public void setAddressUsagesId(DBSequence value) {
        setAttributeInternal(ADDRESSUSAGESID, value);
    }

    /**
     * Gets the attribute value for ASSOCIATED_OWNER_ID using the alias name AssociatedOwnerId.
     * @return the ASSOCIATED_OWNER_ID
     */
    public Number getAssociatedOwnerId() {
        return (Number) getAttributeInternal(ASSOCIATEDOWNERID);
    }

    /**
     * Sets <code>value</code> as attribute value for ASSOCIATED_OWNER_ID using the alias name AssociatedOwnerId.
     * @param value value to set the ASSOCIATED_OWNER_ID
     */
    public void setAssociatedOwnerId(Number value) {
        setAttributeInternal(ASSOCIATEDOWNERID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for EXPIRED_FLAG using the alias name ExpiredFlag.
     * @return the EXPIRED_FLAG
     */
    public String getExpiredFlag() {
        return (String) getAttributeInternal(EXPIREDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for EXPIRED_FLAG using the alias name ExpiredFlag.
     * @param value value to set the EXPIRED_FLAG
     */
    public void setExpiredFlag(String value) {
        setAttributeInternal(EXPIREDFLAG, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_ID using the alias name ObjectVersionId.
     * @return the OBJECT_VERSION_ID
     */
    public Number getObjectVersionId() {
        return (Number) getAttributeInternal(OBJECTVERSIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION_ID using the alias name ObjectVersionId.
     * @param value value to set the OBJECT_VERSION_ID
     */
    public void setObjectVersionId(Number value) {
        setAttributeInternal(OBJECTVERSIONID, value);
    }

    /**
     * Gets the attribute value for OWNER_TYPE_CODE using the alias name OwnerTypeCode.
     * @return the OWNER_TYPE_CODE
     */
    public String getOwnerTypeCode() {
        return (String) getAttributeInternal(OWNERTYPECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for OWNER_TYPE_CODE using the alias name OwnerTypeCode.
     * @param value value to set the OWNER_TYPE_CODE
     */
    public void setOwnerTypeCode(String value) {
        setAttributeInternal(OWNERTYPECODE, value);
    }

    /**
     * Gets the attribute value for USAGE_TYPE_CODE using the alias name UsageTypeCode.
     * @return the USAGE_TYPE_CODE
     */
    public String getUsageTypeCode() {
        return (String) getAttributeInternal(USAGETYPECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for USAGE_TYPE_CODE using the alias name UsageTypeCode.
     * @param value value to set the USAGE_TYPE_CODE
     */
    public void setUsageTypeCode(String value) {
        setAttributeInternal(USAGETYPECODE, value);
    }

    /**
     * Gets the attribute value for ADDRESS1 using the alias name Address1.
     * @return the ADDRESS1
     */
    public String getAddress1() {
        return (String) getAttributeInternal(ADDRESS1);
    }

    /**
     * Sets <code>value</code> as attribute value for ADDRESS1 using the alias name Address1.
     * @param value value to set the ADDRESS1
     */
    public void setAddress1(String value) {
        setAttributeInternal(ADDRESS1, value);
    }

    /**
     * Gets the attribute value for ADDRESS2 using the alias name Address2.
     * @return the ADDRESS2
     */
    public String getAddress2() {
        return (String) getAttributeInternal(ADDRESS2);
    }

    /**
     * Sets <code>value</code> as attribute value for ADDRESS2 using the alias name Address2.
     * @param value value to set the ADDRESS2
     */
    public void setAddress2(String value) {
        setAttributeInternal(ADDRESS2, value);
    }

    /**
     * Gets the attribute value for ADDRESS_ID using the alias name AddressId1.
     * @return the ADDRESS_ID
     */
    public DBSequence getAddressId1() {
        return (DBSequence)getAttributeInternal(ADDRESSID1);
    }

    /**
     * Sets <code>value</code> as attribute value for ADDRESS_ID using the alias name AddressId1.
     * @param value value to set the ADDRESS_ID
     */
    public void setAddressId1(DBSequence value) {
        setAttributeInternal(ADDRESSID1, value);
    }

    /**
     * Gets the attribute value for CITY using the alias name City.
     * @return the CITY
     */
    public String getCity() {
        return (String) getAttributeInternal(CITY);
    }

    /**
     * Sets <code>value</code> as attribute value for CITY using the alias name City.
     * @param value value to set the CITY
     */
    public void setCity(String value) {
        setAttributeInternal(CITY, value);
    }

    /**
     * Gets the attribute value for COUNTRY_ID using the alias name CountryId.
     * @return the COUNTRY_ID
     */
    public String getCountryId() {
        return (String) getAttributeInternal(COUNTRYID);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY_ID using the alias name CountryId.
     * @param value value to set the COUNTRY_ID
     */
    public void setCountryId(String value) {
        setAttributeInternal(COUNTRYID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy1.
     * @return the CREATED_BY
     */
    public String getCreatedBy1() {
        return (String) getAttributeInternal(CREATEDBY1);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy1.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy1(String value) {
        setAttributeInternal(CREATEDBY1, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate1.
     * @return the CREATION_DATE
     */
    public Date getCreationDate1() {
        return (Date) getAttributeInternal(CREATIONDATE1);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate1.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate1(Date value) {
        setAttributeInternal(CREATIONDATE1, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate1.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate1() {
        return (Date) getAttributeInternal(LASTUPDATEDATE1);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate1.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate1(Date value) {
        setAttributeInternal(LASTUPDATEDATE1, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy1.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy1() {
        return (String) getAttributeInternal(LASTUPDATEDBY1);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy1.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy1(String value) {
        setAttributeInternal(LASTUPDATEDBY1, value);
    }

    /**
     * Gets the attribute value for LATITUDE using the alias name Latitude.
     * @return the LATITUDE
     */
    public Number getLatitude() {
        return (Number) getAttributeInternal(LATITUDE);
    }

    /**
     * Sets <code>value</code> as attribute value for LATITUDE using the alias name Latitude.
     * @param value value to set the LATITUDE
     */
    public void setLatitude(Number value) {
        setAttributeInternal(LATITUDE, value);
    }

    /**
     * Gets the attribute value for LONGITUDE using the alias name Longitude.
     * @return the LONGITUDE
     */
    public Number getLongitude() {
        return (Number) getAttributeInternal(LONGITUDE);
    }

    /**
     * Sets <code>value</code> as attribute value for LONGITUDE using the alias name Longitude.
     * @param value value to set the LONGITUDE
     */
    public void setLongitude(Number value) {
        setAttributeInternal(LONGITUDE, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_ID using the alias name ObjectVersionId1.
     * @return the OBJECT_VERSION_ID
     */
    public Number getObjectVersionId1() {
        return (Number) getAttributeInternal(OBJECTVERSIONID1);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION_ID using the alias name ObjectVersionId1.
     * @param value value to set the OBJECT_VERSION_ID
     */
    public void setObjectVersionId1(Number value) {
        setAttributeInternal(OBJECTVERSIONID1, value);
    }

    /**
     * Gets the attribute value for POSTAL_CODE using the alias name PostalCode.
     * @return the POSTAL_CODE
     */
    public String getPostalCode() {
        return (String) getAttributeInternal(POSTALCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTAL_CODE using the alias name PostalCode.
     * @param value value to set the POSTAL_CODE
     */
    public void setPostalCode(String value) {
        setAttributeInternal(POSTALCODE, value);
    }

    /**
     * Gets the attribute value for STATE_PROVINCE using the alias name StateProvince.
     * @return the STATE_PROVINCE
     */
    public String getStateProvince() {
        return (String) getAttributeInternal(STATEPROVINCE);
    }

    /**
     * Sets <code>value</code> as attribute value for STATE_PROVINCE using the alias name StateProvince.
     * @param value value to set the STATE_PROVINCE
     */
    public void setStateProvince(String value) {
        setAttributeInternal(STATEPROVINCE, value);
    }

    /**
     * Gets the attribute value for COUNTRY_NAME using the alias name CountryName.
     * @return the COUNTRY_NAME
     */
    public String getCountryName() {
        return (String) getAttributeInternal(COUNTRYNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY_NAME using the alias name CountryName.
     * @param value value to set the COUNTRY_NAME
     */
    public void setCountryName(String value) {
        setAttributeInternal(COUNTRYNAME, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy2.
     * @return the CREATED_BY
     */
    public String getCreatedBy2() {
        return (String) getAttributeInternal(CREATEDBY2);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy2.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy2(String value) {
        setAttributeInternal(CREATEDBY2, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate2.
     * @return the CREATION_DATE
     */
    public Date getCreationDate2() {
        return (Date) getAttributeInternal(CREATIONDATE2);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate2.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate2(Date value) {
        setAttributeInternal(CREATIONDATE2, value);
    }

    /**
     * Gets the attribute value for ISO_COUNTRY_CODE using the alias name IsoCountryCode.
     * @return the ISO_COUNTRY_CODE
     */
    public String getIsoCountryCode() {
        return (String) getAttributeInternal(ISOCOUNTRYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for ISO_COUNTRY_CODE using the alias name IsoCountryCode.
     * @param value value to set the ISO_COUNTRY_CODE
     */
    public void setIsoCountryCode(String value) {
        setAttributeInternal(ISOCOUNTRYCODE, value);
    }

    /**
     * Gets the attribute value for LANGUAGE using the alias name Language.
     * @return the LANGUAGE
     */
    public String getLanguage() {
        return (String) getAttributeInternal(LANGUAGE);
    }

    /**
     * Sets <code>value</code> as attribute value for LANGUAGE using the alias name Language.
     * @param value value to set the LANGUAGE
     */
    public void setLanguage(String value) {
        setAttributeInternal(LANGUAGE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate2.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate2() {
        return (Date) getAttributeInternal(LASTUPDATEDATE2);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate2.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate2(Date value) {
        setAttributeInternal(LASTUPDATEDATE2, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy2.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy2() {
        return (String) getAttributeInternal(LASTUPDATEDBY2);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy2.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy2(String value) {
        setAttributeInternal(LASTUPDATEDBY2, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_ID using the alias name ObjectVersionId2.
     * @return the OBJECT_VERSION_ID
     */
    public Number getObjectVersionId2() {
        return (Number) getAttributeInternal(OBJECTVERSIONID2);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION_ID using the alias name ObjectVersionId2.
     * @param value value to set the OBJECT_VERSION_ID
     */
    public void setObjectVersionId2(Number value) {
        setAttributeInternal(OBJECTVERSIONID2, value);
    }

    /**
     * Gets the attribute value for SOURCE_LANG using the alias name SourceLang.
     * @return the SOURCE_LANG
     */
    public String getSourceLang() {
        return (String) getAttributeInternal(SOURCELANG);
    }

    /**
     * Sets <code>value</code> as attribute value for SOURCE_LANG using the alias name SourceLang.
     * @param value value to set the SOURCE_LANG
     */
    public void setSourceLang(String value) {
        setAttributeInternal(SOURCELANG, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy3.
     * @return the CREATED_BY
     */
    public String getCreatedBy3() {
        return (String) getAttributeInternal(CREATEDBY3);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy3.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy3(String value) {
        setAttributeInternal(CREATEDBY3, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate3.
     * @return the CREATION_DATE
     */
    public Date getCreationDate3() {
        return (Date) getAttributeInternal(CREATIONDATE3);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate3.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate3(Date value) {
        setAttributeInternal(CREATIONDATE3, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for LANGUAGE using the alias name Language1.
     * @return the LANGUAGE
     */
    public String getLanguage1() {
        return (String) getAttributeInternal(LANGUAGE1);
    }

    /**
     * Sets <code>value</code> as attribute value for LANGUAGE using the alias name Language1.
     * @param value value to set the LANGUAGE
     */
    public void setLanguage1(String value) {
        setAttributeInternal(LANGUAGE1, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate3.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate3() {
        return (Date) getAttributeInternal(LASTUPDATEDATE3);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate3.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate3(Date value) {
        setAttributeInternal(LASTUPDATEDATE3, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy3.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy3() {
        return (String) getAttributeInternal(LASTUPDATEDBY3);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy3.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy3(String value) {
        setAttributeInternal(LASTUPDATEDBY3, value);
    }

    /**
     * Gets the attribute value for LOOKUP_CODE using the alias name LookupCode.
     * @return the LOOKUP_CODE
     */
    public String getLookupCode() {
        return (String) getAttributeInternal(LOOKUPCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for LOOKUP_CODE using the alias name LookupCode.
     * @param value value to set the LOOKUP_CODE
     */
    public void setLookupCode(String value) {
        setAttributeInternal(LOOKUPCODE, value);
    }

    /**
     * Gets the attribute value for LOOKUP_TYPE using the alias name LookupType.
     * @return the LOOKUP_TYPE
     */
    public String getLookupType() {
        return (String) getAttributeInternal(LOOKUPTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for LOOKUP_TYPE using the alias name LookupType.
     * @param value value to set the LOOKUP_TYPE
     */
    public void setLookupType(String value) {
        setAttributeInternal(LOOKUPTYPE, value);
    }

    /**
     * Gets the attribute value for MEANING using the alias name Meaning.
     * @return the MEANING
     */
    public String getMeaning() {
        return (String) getAttributeInternal(MEANING);
    }

    /**
     * Sets <code>value</code> as attribute value for MEANING using the alias name Meaning.
     * @param value value to set the MEANING
     */
    public void setMeaning(String value) {
        setAttributeInternal(MEANING, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_ID using the alias name ObjectVersionId3.
     * @return the OBJECT_VERSION_ID
     */
    public Number getObjectVersionId3() {
        return (Number) getAttributeInternal(OBJECTVERSIONID3);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION_ID using the alias name ObjectVersionId3.
     * @param value value to set the OBJECT_VERSION_ID
     */
    public void setObjectVersionId3(Number value) {
        setAttributeInternal(OBJECTVERSIONID3, value);
    }

    /**
     * Gets the attribute value for SOURCE_LANG using the alias name SourceLang1.
     * @return the SOURCE_LANG
     */
    public String getSourceLang1() {
        return (String) getAttributeInternal(SOURCELANG1);
    }

    /**
     * Sets <code>value</code> as attribute value for SOURCE_LANG using the alias name SourceLang1.
     * @param value value to set the SOURCE_LANG
     */
    public void setSourceLang1(String value) {
        setAttributeInternal(SOURCELANG1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AddressLabel.
     * @return the AddressLabel
     */
    public String getAddressLabel() {
        return (String) getAttributeInternal(ADDRESSLABEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AddressLabel.
     * @param value value to set the  AddressLabel
     */
    public void setAddressLabel(String value) {
        setAttributeInternal(ADDRESSLABEL, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupCodeSUsageType.
     */
    public RowSet getLookupCodeSUsageType() {
        return (RowSet)getAttributeInternal(LOOKUPCODESUSAGETYPE);
    }
    protected void create(AttributeList attributeList) {
            // The view row will already have created "blank" entity instances
            AddressesEOImpl newAddress = this.getAddressesEO();
            AddressUsagesEOImpl newAddressUsage = this.getAddressUsagesEO();

            try {
                // Let Address "blank" entity instance to do programmatic defaulting
                newAddress.create(attributeList);
                // Let AddressUsage "blank" entity instance to do programmatic
                // defaulting passing in new AddressesImpl instance so its attributes
                // are available to the AdressUsagesImpl's create method.
                newAddressUsage.create(newAddress);
                System.out.println("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"+newAddress.getAddressId().getValue());
                newAddressUsage.setAddressId(new Number((newAddress.getAddressId().getValue())));  
                // Set the entity state back to STATUS_INITIALIZED
                newAddressUsage.setNewRowState(STATUS_INITIALIZED);
                if(newAddress != null && newAddress.getAddressId() != null){
                    newAddressUsage.setAddressId(newAddress.getAddressId().getSequenceNumber());
                }
            
            } catch (JboException ex) {
                newAddress.revert();
                newAddressUsage.revert();
                throw ex;
            } catch (Exception otherEx) {
                newAddress.revert();
                newAddressUsage.revert();
                throw /* EO Row? / / EO Name / / Details */new RowCreateException(true, 
                                                                                      "Addresses", 
                                                                                 otherEx);
            }
        }
    /**
     * Gets the view accessor <code>RowSet</code> CountriesVO1.
     */
    public RowSet getCountriesVO1() {
        return (RowSet)getAttributeInternal(COUNTRIESVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
