package model.mwgl.vo;

import model.mwgl.eo.OrdersEOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 17 15:53:10 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OrdersVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        OrderId {
            public Object get(OrdersVORowImpl obj) {
                return obj.getOrderId();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setOrderId((DBSequence)value);
            }
        }
        ,
        OrderDate {
            public Object get(OrdersVORowImpl obj) {
                return obj.getOrderDate();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setOrderDate((Date)value);
            }
        }
        ,
        OrderShippedDate {
            public Object get(OrdersVORowImpl obj) {
                return obj.getOrderShippedDate();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setOrderShippedDate((Date)value);
            }
        }
        ,
        OrderStatusCode {
            public Object get(OrdersVORowImpl obj) {
                return obj.getOrderStatusCode();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setOrderStatusCode((String)value);
            }
        }
        ,
        OrderTotal {
            public Object get(OrdersVORowImpl obj) {
                return obj.getOrderTotal();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setOrderTotal((Number)value);
            }
        }
        ,
        CustomerId {
            public Object get(OrdersVORowImpl obj) {
                return obj.getCustomerId();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setCustomerId((Number)value);
            }
        }
        ,
        ShipToName {
            public Object get(OrdersVORowImpl obj) {
                return obj.getShipToName();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setShipToName((String)value);
            }
        }
        ,
        ShipToAddressId {
            public Object get(OrdersVORowImpl obj) {
                return obj.getShipToAddressId();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setShipToAddressId((Number)value);
            }
        }
        ,
        ShipToPhoneNumber {
            public Object get(OrdersVORowImpl obj) {
                return obj.getShipToPhoneNumber();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setShipToPhoneNumber((String)value);
            }
        }
        ,
        ShippingOptionId {
            public Object get(OrdersVORowImpl obj) {
                return obj.getShippingOptionId();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setShippingOptionId((Number)value);
            }
        }
        ,
        PaymentOptionId {
            public Object get(OrdersVORowImpl obj) {
                return obj.getPaymentOptionId();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setPaymentOptionId((Number)value);
            }
        }
        ,
        DiscountId {
            public Object get(OrdersVORowImpl obj) {
                return obj.getDiscountId();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setDiscountId((Number)value);
            }
        }
        ,
        CouponId {
            public Object get(OrdersVORowImpl obj) {
                return obj.getCouponId();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setCouponId((Number)value);
            }
        }
        ,
        FreeShippingFlag {
            public Object get(OrdersVORowImpl obj) {
                return obj.getFreeShippingFlag();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setFreeShippingFlag((String)value);
            }
        }
        ,
        CustomerCollectFlag {
            public Object get(OrdersVORowImpl obj) {
                return obj.getCustomerCollectFlag();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setCustomerCollectFlag((String)value);
            }
        }
        ,
        CollectionWarehouseId {
            public Object get(OrdersVORowImpl obj) {
                return obj.getCollectionWarehouseId();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setCollectionWarehouseId((Number)value);
            }
        }
        ,
        GiftwrapFlag {
            public Object get(OrdersVORowImpl obj) {
                return obj.getGiftwrapFlag();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setGiftwrapFlag((String)value);
            }
        }
        ,
        GiftwrapMessage {
            public Object get(OrdersVORowImpl obj) {
                return obj.getGiftwrapMessage();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setGiftwrapMessage((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(OrdersVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(OrdersVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(OrdersVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(OrdersVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        ObjectVersionId {
            public Object get(OrdersVORowImpl obj) {
                return obj.getObjectVersionId();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setObjectVersionId((Number)value);
            }
        }
        ,
        TotalShippingCost {
            public Object get(OrdersVORowImpl obj) {
                return obj.getTotalShippingCost();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setTotalShippingCost((Double)value);
            }
        }
        ,
        CalculatedOrderTotal {
            public Object get(OrdersVORowImpl obj) {
                return obj.getCalculatedOrderTotal();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setCalculatedOrderTotal((Double)value);
            }
        }
        ,
        CalculatedOrderTotal1 {
            public Object get(OrdersVORowImpl obj) {
                return obj.getCalculatedOrderTotal1();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setCalculatedOrderTotal1((Double)value);
            }
        }
        ,
        DiscountAmount {
            public Object get(OrdersVORowImpl obj) {
                return obj.getDiscountAmount();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setDiscountAmount((Double)value);
            }
        }
        ,
        InvoiceTotal {
            public Object get(OrdersVORowImpl obj) {
                return obj.getInvoiceTotal();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setInvoiceTotal((Double)value);
            }
        }
        ,
        isCancelable {
            public Object get(OrdersVORowImpl obj) {
                return obj.getisCancelable();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setisCancelable((Boolean)value);
            }
        }
        ,
        OrderItemsVO {
            public Object get(OrdersVORowImpl obj) {
                return obj.getOrderItemsVO();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AddressesVO {
            public Object get(OrdersVORowImpl obj) {
                return obj.getAddressesVO();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PaymentOptionsVO {
            public Object get(OrdersVORowImpl obj) {
                return obj.getPaymentOptionsVO();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ShippingOptionsView1 {
            public Object get(OrdersVORowImpl obj) {
                return obj.getShippingOptionsView1();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ShippingOptionsView2 {
            public Object get(OrdersVORowImpl obj) {
                return obj.getShippingOptionsView2();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PaymentOptionsVO1 {
            public Object get(OrdersVORowImpl obj) {
                return obj.getPaymentOptionsVO1();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AddressAndUsageVO1 {
            public Object get(OrdersVORowImpl obj) {
                return obj.getAddressAndUsageVO1();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(OrdersVORowImpl object);

        public abstract void put(OrdersVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ORDERID = AttributesEnum.OrderId.index();
    public static final int ORDERDATE = AttributesEnum.OrderDate.index();
    public static final int ORDERSHIPPEDDATE = AttributesEnum.OrderShippedDate.index();
    public static final int ORDERSTATUSCODE = AttributesEnum.OrderStatusCode.index();
    public static final int ORDERTOTAL = AttributesEnum.OrderTotal.index();
    public static final int CUSTOMERID = AttributesEnum.CustomerId.index();
    public static final int SHIPTONAME = AttributesEnum.ShipToName.index();
    public static final int SHIPTOADDRESSID = AttributesEnum.ShipToAddressId.index();
    public static final int SHIPTOPHONENUMBER = AttributesEnum.ShipToPhoneNumber.index();
    public static final int SHIPPINGOPTIONID = AttributesEnum.ShippingOptionId.index();
    public static final int PAYMENTOPTIONID = AttributesEnum.PaymentOptionId.index();
    public static final int DISCOUNTID = AttributesEnum.DiscountId.index();
    public static final int COUPONID = AttributesEnum.CouponId.index();
    public static final int FREESHIPPINGFLAG = AttributesEnum.FreeShippingFlag.index();
    public static final int CUSTOMERCOLLECTFLAG = AttributesEnum.CustomerCollectFlag.index();
    public static final int COLLECTIONWAREHOUSEID = AttributesEnum.CollectionWarehouseId.index();
    public static final int GIFTWRAPFLAG = AttributesEnum.GiftwrapFlag.index();
    public static final int GIFTWRAPMESSAGE = AttributesEnum.GiftwrapMessage.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int OBJECTVERSIONID = AttributesEnum.ObjectVersionId.index();
    public static final int TOTALSHIPPINGCOST = AttributesEnum.TotalShippingCost.index();
    public static final int CALCULATEDORDERTOTAL = AttributesEnum.CalculatedOrderTotal.index();
    public static final int CALCULATEDORDERTOTAL1 = AttributesEnum.CalculatedOrderTotal1.index();
    public static final int DISCOUNTAMOUNT = AttributesEnum.DiscountAmount.index();
    public static final int INVOICETOTAL = AttributesEnum.InvoiceTotal.index();
    public static final int ISCANCELABLE = AttributesEnum.isCancelable.index();
    public static final int ORDERITEMSVO = AttributesEnum.OrderItemsVO.index();
    public static final int ADDRESSESVO = AttributesEnum.AddressesVO.index();
    public static final int PAYMENTOPTIONSVO = AttributesEnum.PaymentOptionsVO.index();
    public static final int SHIPPINGOPTIONSVIEW1 = AttributesEnum.ShippingOptionsView1.index();
    public static final int SHIPPINGOPTIONSVIEW2 = AttributesEnum.ShippingOptionsView2.index();
    public static final int PAYMENTOPTIONSVO1 = AttributesEnum.PaymentOptionsVO1.index();
    public static final int ADDRESSANDUSAGEVO1 = AttributesEnum.AddressAndUsageVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OrdersVORowImpl() {
    }

    /**
     * Gets OrdersEO entity object.
     * @return the OrdersEO
     */
    public OrdersEOImpl getOrdersEO() {
        return (OrdersEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for ORDER_ID using the alias name OrderId.
     * @return the ORDER_ID
     */
    public DBSequence getOrderId() {
        return (DBSequence) getAttributeInternal(ORDERID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORDER_ID using the alias name OrderId.
     * @param value value to set the ORDER_ID
     */
    public void setOrderId(DBSequence value) {
        setAttributeInternal(ORDERID, value);
    }

    /**
     * Gets the attribute value for ORDER_DATE using the alias name OrderDate.
     * @return the ORDER_DATE
     */
    public Date getOrderDate() {
        return (Date) getAttributeInternal(ORDERDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ORDER_DATE using the alias name OrderDate.
     * @param value value to set the ORDER_DATE
     */
    public void setOrderDate(Date value) {
        setAttributeInternal(ORDERDATE, value);
    }

    /**
     * Gets the attribute value for ORDER_SHIPPED_DATE using the alias name OrderShippedDate.
     * @return the ORDER_SHIPPED_DATE
     */
    public Date getOrderShippedDate() {
        return (Date) getAttributeInternal(ORDERSHIPPEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ORDER_SHIPPED_DATE using the alias name OrderShippedDate.
     * @param value value to set the ORDER_SHIPPED_DATE
     */
    public void setOrderShippedDate(Date value) {
        setAttributeInternal(ORDERSHIPPEDDATE, value);
    }

    /**
     * Gets the attribute value for ORDER_STATUS_CODE using the alias name OrderStatusCode.
     * @return the ORDER_STATUS_CODE
     */
    public String getOrderStatusCode() {
        return (String) getAttributeInternal(ORDERSTATUSCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for ORDER_STATUS_CODE using the alias name OrderStatusCode.
     * @param value value to set the ORDER_STATUS_CODE
     */
    public void setOrderStatusCode(String value) {
        setAttributeInternal(ORDERSTATUSCODE, value);
    }

    /**
     * Gets the attribute value for ORDER_TOTAL using the alias name OrderTotal.
     * @return the ORDER_TOTAL
     */
    public Number getOrderTotal() {
        return (Number) getAttributeInternal(ORDERTOTAL);
    }

    /**
     * Sets <code>value</code> as attribute value for ORDER_TOTAL using the alias name OrderTotal.
     * @param value value to set the ORDER_TOTAL
     */
    public void setOrderTotal(Number value) {
        setAttributeInternal(ORDERTOTAL, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_ID using the alias name CustomerId.
     * @return the CUSTOMER_ID
     */
    public Number getCustomerId() {
        return (Number) getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_ID using the alias name CustomerId.
     * @param value value to set the CUSTOMER_ID
     */
    public void setCustomerId(Number value) {
        setAttributeInternal(CUSTOMERID, value);
    }

    /**
     * Gets the attribute value for SHIP_TO_NAME using the alias name ShipToName.
     * @return the SHIP_TO_NAME
     */
    public String getShipToName() {
        return (String) getAttributeInternal(SHIPTONAME);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_TO_NAME using the alias name ShipToName.
     * @param value value to set the SHIP_TO_NAME
     */
    public void setShipToName(String value) {
        setAttributeInternal(SHIPTONAME, value);
    }

    /**
     * Gets the attribute value for SHIP_TO_ADDRESS_ID using the alias name ShipToAddressId.
     * @return the SHIP_TO_ADDRESS_ID
     */
    public Number getShipToAddressId() {
        return (Number) getAttributeInternal(SHIPTOADDRESSID);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_TO_ADDRESS_ID using the alias name ShipToAddressId.
     * @param value value to set the SHIP_TO_ADDRESS_ID
     */
    public void setShipToAddressId(Number value) {
        setAttributeInternal(SHIPTOADDRESSID, value);
    }

    /**
     * Gets the attribute value for SHIP_TO_PHONE_NUMBER using the alias name ShipToPhoneNumber.
     * @return the SHIP_TO_PHONE_NUMBER
     */
    public String getShipToPhoneNumber() {
        return (String) getAttributeInternal(SHIPTOPHONENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_TO_PHONE_NUMBER using the alias name ShipToPhoneNumber.
     * @param value value to set the SHIP_TO_PHONE_NUMBER
     */
    public void setShipToPhoneNumber(String value) {
        setAttributeInternal(SHIPTOPHONENUMBER, value);
    }

    /**
     * Gets the attribute value for SHIPPING_OPTION_ID using the alias name ShippingOptionId.
     * @return the SHIPPING_OPTION_ID
     */
    public Number getShippingOptionId() {
        return (Number) getAttributeInternal(SHIPPINGOPTIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIPPING_OPTION_ID using the alias name ShippingOptionId.
     * @param value value to set the SHIPPING_OPTION_ID
     */
    public void setShippingOptionId(Number value) {
        setAttributeInternal(SHIPPINGOPTIONID, value);
    }

    /**
     * Gets the attribute value for PAYMENT_OPTION_ID using the alias name PaymentOptionId.
     * @return the PAYMENT_OPTION_ID
     */
    public Number getPaymentOptionId() {
        return (Number) getAttributeInternal(PAYMENTOPTIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_OPTION_ID using the alias name PaymentOptionId.
     * @param value value to set the PAYMENT_OPTION_ID
     */
    public void setPaymentOptionId(Number value) {
        setAttributeInternal(PAYMENTOPTIONID, value);
    }

    /**
     * Gets the attribute value for DISCOUNT_ID using the alias name DiscountId.
     * @return the DISCOUNT_ID
     */
    public Number getDiscountId() {
        return (Number) getAttributeInternal(DISCOUNTID);
    }

    /**
     * Sets <code>value</code> as attribute value for DISCOUNT_ID using the alias name DiscountId.
     * @param value value to set the DISCOUNT_ID
     */
    public void setDiscountId(Number value) {
        setAttributeInternal(DISCOUNTID, value);
    }

    /**
     * Gets the attribute value for COUPON_ID using the alias name CouponId.
     * @return the COUPON_ID
     */
    public Number getCouponId() {
        return (Number) getAttributeInternal(COUPONID);
    }

    /**
     * Sets <code>value</code> as attribute value for COUPON_ID using the alias name CouponId.
     * @param value value to set the COUPON_ID
     */
    public void setCouponId(Number value) {
        setAttributeInternal(COUPONID, value);
    }

    /**
     * Gets the attribute value for FREE_SHIPPING_FLAG using the alias name FreeShippingFlag.
     * @return the FREE_SHIPPING_FLAG
     */
    public String getFreeShippingFlag() {
        return (String) getAttributeInternal(FREESHIPPINGFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for FREE_SHIPPING_FLAG using the alias name FreeShippingFlag.
     * @param value value to set the FREE_SHIPPING_FLAG
     */
    public void setFreeShippingFlag(String value) {
        setAttributeInternal(FREESHIPPINGFLAG, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_COLLECT_FLAG using the alias name CustomerCollectFlag.
     * @return the CUSTOMER_COLLECT_FLAG
     */
    public String getCustomerCollectFlag() {
        return (String) getAttributeInternal(CUSTOMERCOLLECTFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_COLLECT_FLAG using the alias name CustomerCollectFlag.
     * @param value value to set the CUSTOMER_COLLECT_FLAG
     */
    public void setCustomerCollectFlag(String value) {
        setAttributeInternal(CUSTOMERCOLLECTFLAG, value);
    }

    /**
     * Gets the attribute value for COLLECTION_WAREHOUSE_ID using the alias name CollectionWarehouseId.
     * @return the COLLECTION_WAREHOUSE_ID
     */
    public Number getCollectionWarehouseId() {
        return (Number) getAttributeInternal(COLLECTIONWAREHOUSEID);
    }

    /**
     * Sets <code>value</code> as attribute value for COLLECTION_WAREHOUSE_ID using the alias name CollectionWarehouseId.
     * @param value value to set the COLLECTION_WAREHOUSE_ID
     */
    public void setCollectionWarehouseId(Number value) {
        setAttributeInternal(COLLECTIONWAREHOUSEID, value);
    }

    /**
     * Gets the attribute value for GIFTWRAP_FLAG using the alias name GiftwrapFlag.
     * @return the GIFTWRAP_FLAG
     */
    public String getGiftwrapFlag() {
        return (String) getAttributeInternal(GIFTWRAPFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for GIFTWRAP_FLAG using the alias name GiftwrapFlag.
     * @param value value to set the GIFTWRAP_FLAG
     */
    public void setGiftwrapFlag(String value) {
        setAttributeInternal(GIFTWRAPFLAG, value);
    }

    /**
     * Gets the attribute value for GIFTWRAP_MESSAGE using the alias name GiftwrapMessage.
     * @return the GIFTWRAP_MESSAGE
     */
    public String getGiftwrapMessage() {
        return (String) getAttributeInternal(GIFTWRAPMESSAGE);
    }

    /**
     * Sets <code>value</code> as attribute value for GIFTWRAP_MESSAGE using the alias name GiftwrapMessage.
     * @param value value to set the GIFTWRAP_MESSAGE
     */
    public void setGiftwrapMessage(String value) {
        setAttributeInternal(GIFTWRAPMESSAGE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_ID using the alias name ObjectVersionId.
     * @return the OBJECT_VERSION_ID
     */
    public Number getObjectVersionId() {
        return (Number) getAttributeInternal(OBJECTVERSIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION_ID using the alias name ObjectVersionId.
     * @param value value to set the OBJECT_VERSION_ID
     */
    public void setObjectVersionId(Number value) {
        setAttributeInternal(OBJECTVERSIONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalShippingCost.
     * @return the TotalShippingCost
     */
    public Double getTotalShippingCost() {
        return (Double) getAttributeInternal(TOTALSHIPPINGCOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalShippingCost.
     * @param value value to set the  TotalShippingCost
     */
    public void setTotalShippingCost(Double value) {
        setAttributeInternal(TOTALSHIPPINGCOST, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CalculatedOrderTotal.
     * @return the CalculatedOrderTotal
     */
    public Double getCalculatedOrderTotal() {
        return (Double) getAttributeInternal(CALCULATEDORDERTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CalculatedOrderTotal.
     * @param value value to set the  CalculatedOrderTotal
     */
    public void setCalculatedOrderTotal(Double value) {
        setAttributeInternal(CALCULATEDORDERTOTAL, value);
    }

    /**
     * Gets the attribute value for CALCULATED_ORDER_TOTAL using the alias name CalculatedOrderTotal1.
     * @return the CALCULATED_ORDER_TOTAL
     */
    public Double getCalculatedOrderTotal1() {
        return (Double) getAttributeInternal(CALCULATEDORDERTOTAL1);
    }

    /**
     * Sets <code>value</code> as attribute value for CALCULATED_ORDER_TOTAL using the alias name CalculatedOrderTotal1.
     * @param value value to set the CALCULATED_ORDER_TOTAL
     */
    public void setCalculatedOrderTotal1(Double value) {
        setAttributeInternal(CALCULATEDORDERTOTAL1, value);
    }

    /**
     * Gets the attribute value for DISCOUNT_AMOUNT using the alias name DiscountAmount.
     * @return the DISCOUNT_AMOUNT
     */
    public Double getDiscountAmount() {
        return (Double) getAttributeInternal(DISCOUNTAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for DISCOUNT_AMOUNT using the alias name DiscountAmount.
     * @param value value to set the DISCOUNT_AMOUNT
     */
    public void setDiscountAmount(Double value) {
        setAttributeInternal(DISCOUNTAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceTotal.
     * @return the InvoiceTotal
     */
    public Double getInvoiceTotal() {
        return (Double) getAttributeInternal(INVOICETOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoiceTotal.
     * @param value value to set the  InvoiceTotal
     */
    public void setInvoiceTotal(Double value) {
        setAttributeInternal(INVOICETOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute isCancelable.
     * @return the isCancelable
     */
    public Boolean getisCancelable() {
        return (Boolean) getAttributeInternal(ISCANCELABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute isCancelable.
     * @param value value to set the  isCancelable
     */
    public void setisCancelable(Boolean value) {
        setAttributeInternal(ISCANCELABLE, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link OrderItemsVO.
     */
    public RowIterator getOrderItemsVO() {
        return (RowIterator)getAttributeInternal(ORDERITEMSVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link AddressesVO.
     */
    public RowIterator getAddressesVO() {
        return (RowIterator)getAttributeInternal(ADDRESSESVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PaymentOptionsVO.
     */
    public RowIterator getPaymentOptionsVO() {
        return (RowIterator)getAttributeInternal(PAYMENTOPTIONSVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ShippingOptionsView1.
     */
    public RowSet getShippingOptionsView1() {
        return (RowSet)getAttributeInternal(SHIPPINGOPTIONSVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ShippingOptionsView2.
     */
    public RowSet getShippingOptionsView2() {
        return (RowSet)getAttributeInternal(SHIPPINGOPTIONSVIEW2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PaymentOptionsVO1.
     */
    public RowSet getPaymentOptionsVO1() {
        return (RowSet)getAttributeInternal(PAYMENTOPTIONSVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AddressAndUsageVO1.
     */
    public RowSet getAddressAndUsageVO1() {
        return (RowSet)getAttributeInternal(ADDRESSANDUSAGEVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
