package model.mwgl.vo;

import model.mwgl.vo.common.OrdersVO;

import oracle.jbo.JboException;
import oracle.jbo.JboExceptionHandler;
import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 05 06:22:18 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OrdersVOImpl extends ViewObjectImpl implements OrdersVO {
    /**
     * This is the default constructor (do not remove).
     */
    public OrdersVOImpl() {
    }
//* 1)get order row
//* 2)check order status pending
//* 3)change status to cancel
//* 4)save changes
//* 5)show failure and suceess messages     
    public void cancelOrdered(){
        Row currentRow = this.getCurrentRow();
        if(currentRow!= null);
        String StatusCode = (String)currentRow.getAttribute("OrderStatusCode");
        if(StatusCode != null && StatusCode.equalsIgnoreCase("PENDING")){
            currentRow.setAttribute("OrderStatusCode","CANCEL");
            this.getDBTransaction().commit();
           }else{
            throw new JboException("You cant cancel this order");
        }

    }
        
        
    }

