package model.mwgl.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 18 16:19:07 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ShippingOptionTranslationsViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ShippingOptionTranslationsViewImpl() {
    }
}
