package model.mwgl.vo.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 30 05:55:13 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AddressAndUsageVORowClient extends RowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AddressAndUsageVORowClient() {
    }

    public Number getAddressId() {
        return (Number)getAttribute("AddressId");
    }

    public void setAddressId(Number value) {
        setAttribute("AddressId", value);
    }

    public DBSequence getAddressUsagesId() {
        return (DBSequence)getAttribute("AddressUsagesId");
    }

    public void setAddressUsagesId(DBSequence value) {
        setAttribute("AddressUsagesId", value);
    }

    public Number getAssociatedOwnerId() {
        return (Number)getAttribute("AssociatedOwnerId");
    }

    public void setAssociatedOwnerId(Number value) {
        setAttribute("AssociatedOwnerId", value);
    }

    public String getCreatedBy() {
        return (String)getAttribute("CreatedBy");
    }

    public void setCreatedBy(String value) {
        setAttribute("CreatedBy", value);
    }

    public Date getCreationDate() {
        return (Date)getAttribute("CreationDate");
    }

    public void setCreationDate(Date value) {
        setAttribute("CreationDate", value);
    }

    public String getExpiredFlag() {
        return (String)getAttribute("ExpiredFlag");
    }

    public void setExpiredFlag(String value) {
        setAttribute("ExpiredFlag", value);
    }

    public Date getLastUpdateDate() {
        return (Date)getAttribute("LastUpdateDate");
    }

    public void setLastUpdateDate(Date value) {
        setAttribute("LastUpdateDate", value);
    }

    public String getLastUpdatedBy() {
        return (String)getAttribute("LastUpdatedBy");
    }

    public void setLastUpdatedBy(String value) {
        setAttribute("LastUpdatedBy", value);
    }

    public Number getObjectVersionId() {
        return (Number)getAttribute("ObjectVersionId");
    }

    public void setObjectVersionId(Number value) {
        setAttribute("ObjectVersionId", value);
    }

    public String getOwnerTypeCode() {
        return (String)getAttribute("OwnerTypeCode");
    }

    public void setOwnerTypeCode(String value) {
        setAttribute("OwnerTypeCode", value);
    }

    public String getUsageTypeCode() {
        return (String)getAttribute("UsageTypeCode");
    }

    public void setUsageTypeCode(String value) {
        setAttribute("UsageTypeCode", value);
    }

    public String getAddress1() {
        return (String)getAttribute("Address1");
    }

    public void setAddress1(String value) {
        setAttribute("Address1", value);
    }

    public String getAddress2() {
        return (String)getAttribute("Address2");
    }

    public void setAddress2(String value) {
        setAttribute("Address2", value);
    }

    public DBSequence getAddressId1() {
        return (DBSequence)getAttribute("AddressId1");
    }

    public void setAddressId1(DBSequence value) {
        setAttribute("AddressId1", value);
    }

    public String getCity() {
        return (String)getAttribute("City");
    }

    public void setCity(String value) {
        setAttribute("City", value);
    }

    public String getCountryId() {
        return (String)getAttribute("CountryId");
    }

    public void setCountryId(String value) {
        setAttribute("CountryId", value);
    }

    public String getCreatedBy1() {
        return (String)getAttribute("CreatedBy1");
    }

    public void setCreatedBy1(String value) {
        setAttribute("CreatedBy1", value);
    }

    public Date getCreationDate1() {
        return (Date)getAttribute("CreationDate1");
    }

    public void setCreationDate1(Date value) {
        setAttribute("CreationDate1", value);
    }

    public Date getLastUpdateDate1() {
        return (Date)getAttribute("LastUpdateDate1");
    }

    public void setLastUpdateDate1(Date value) {
        setAttribute("LastUpdateDate1", value);
    }

    public String getLastUpdatedBy1() {
        return (String)getAttribute("LastUpdatedBy1");
    }

    public void setLastUpdatedBy1(String value) {
        setAttribute("LastUpdatedBy1", value);
    }

    public Number getLatitude() {
        return (Number)getAttribute("Latitude");
    }

    public void setLatitude(Number value) {
        setAttribute("Latitude", value);
    }

    public Number getLongitude() {
        return (Number)getAttribute("Longitude");
    }

    public void setLongitude(Number value) {
        setAttribute("Longitude", value);
    }

    public Number getObjectVersionId1() {
        return (Number)getAttribute("ObjectVersionId1");
    }

    public void setObjectVersionId1(Number value) {
        setAttribute("ObjectVersionId1", value);
    }

    public String getPostalCode() {
        return (String)getAttribute("PostalCode");
    }

    public void setPostalCode(String value) {
        setAttribute("PostalCode", value);
    }

    public String getStateProvince() {
        return (String)getAttribute("StateProvince");
    }

    public void setStateProvince(String value) {
        setAttribute("StateProvince", value);
    }

    public String getCountryName() {
        return (String)getAttribute("CountryName");
    }

    public void setCountryName(String value) {
        setAttribute("CountryName", value);
    }

    public String getCreatedBy2() {
        return (String)getAttribute("CreatedBy2");
    }

    public void setCreatedBy2(String value) {
        setAttribute("CreatedBy2", value);
    }

    public Date getCreationDate2() {
        return (Date)getAttribute("CreationDate2");
    }

    public void setCreationDate2(Date value) {
        setAttribute("CreationDate2", value);
    }

    public String getIsoCountryCode() {
        return (String)getAttribute("IsoCountryCode");
    }

    public void setIsoCountryCode(String value) {
        setAttribute("IsoCountryCode", value);
    }

    public String getLanguage() {
        return (String)getAttribute("Language");
    }

    public void setLanguage(String value) {
        setAttribute("Language", value);
    }

    public Date getLastUpdateDate2() {
        return (Date)getAttribute("LastUpdateDate2");
    }

    public void setLastUpdateDate2(Date value) {
        setAttribute("LastUpdateDate2", value);
    }

    public String getLastUpdatedBy2() {
        return (String)getAttribute("LastUpdatedBy2");
    }

    public void setLastUpdatedBy2(String value) {
        setAttribute("LastUpdatedBy2", value);
    }

    public Number getObjectVersionId2() {
        return (Number)getAttribute("ObjectVersionId2");
    }

    public void setObjectVersionId2(Number value) {
        setAttribute("ObjectVersionId2", value);
    }

    public String getSourceLang() {
        return (String)getAttribute("SourceLang");
    }

    public void setSourceLang(String value) {
        setAttribute("SourceLang", value);
    }

    public String getCreatedBy3() {
        return (String)getAttribute("CreatedBy3");
    }

    public void setCreatedBy3(String value) {
        setAttribute("CreatedBy3", value);
    }

    public Date getCreationDate3() {
        return (Date)getAttribute("CreationDate3");
    }

    public void setCreationDate3(Date value) {
        setAttribute("CreationDate3", value);
    }

    public String getDescription() {
        return (String)getAttribute("Description");
    }

    public void setDescription(String value) {
        setAttribute("Description", value);
    }

    public String getLanguage1() {
        return (String)getAttribute("Language1");
    }

    public void setLanguage1(String value) {
        setAttribute("Language1", value);
    }

    public Date getLastUpdateDate3() {
        return (Date)getAttribute("LastUpdateDate3");
    }

    public void setLastUpdateDate3(Date value) {
        setAttribute("LastUpdateDate3", value);
    }

    public String getLastUpdatedBy3() {
        return (String)getAttribute("LastUpdatedBy3");
    }

    public void setLastUpdatedBy3(String value) {
        setAttribute("LastUpdatedBy3", value);
    }

    public String getLookupCode() {
        return (String)getAttribute("LookupCode");
    }

    public void setLookupCode(String value) {
        setAttribute("LookupCode", value);
    }

    public String getLookupType() {
        return (String)getAttribute("LookupType");
    }

    public void setLookupType(String value) {
        setAttribute("LookupType", value);
    }

    public String getMeaning() {
        return (String)getAttribute("Meaning");
    }

    public void setMeaning(String value) {
        setAttribute("Meaning", value);
    }

    public Number getObjectVersionId3() {
        return (Number)getAttribute("ObjectVersionId3");
    }

    public void setObjectVersionId3(Number value) {
        setAttribute("ObjectVersionId3", value);
    }

    public String getSourceLang1() {
        return (String)getAttribute("SourceLang1");
    }

    public void setSourceLang1(String value) {
        setAttribute("SourceLang1", value);
    }

    public String getAddressLabel() {
        return (String)getAttribute("AddressLabel");
    }

    public void setAddressLabel(String value) {
        setAttribute("AddressLabel", value);
    }
}
