package model.mwgl.vo.client;

import model.mwgl.vo.common.OrdersVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 05 06:31:11 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OrdersVOClient extends ViewUsageImpl implements OrdersVO {
    /**
     * This is the default constructor (do not remove).
     */
    public OrdersVOClient() {
    }

    public void cancelOrdered() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"cancelOrdered",null,null);
        return;
    }
}
