package model.mwgl.vo.common;

import oracle.jbo.Row;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 30 05:55:12 IST 2022
// ---------------------------------------------------------------------
public interface AddressAndUsageVORow extends Row {
    Number getAddressId();

    void setAddressId(Number value);

    DBSequence getAddressUsagesId();

    void setAddressUsagesId(DBSequence value);

    Number getAssociatedOwnerId();

    void setAssociatedOwnerId(Number value);

    String getCreatedBy();

    void setCreatedBy(String value);

    Date getCreationDate();

    void setCreationDate(Date value);

    String getExpiredFlag();

    void setExpiredFlag(String value);

    Date getLastUpdateDate();

    void setLastUpdateDate(Date value);

    String getLastUpdatedBy();

    void setLastUpdatedBy(String value);

    Number getObjectVersionId();

    void setObjectVersionId(Number value);

    String getOwnerTypeCode();

    void setOwnerTypeCode(String value);

    String getUsageTypeCode();

    void setUsageTypeCode(String value);

    String getAddress1();

    void setAddress1(String value);

    String getAddress2();

    void setAddress2(String value);

    DBSequence getAddressId1();

    void setAddressId1(DBSequence value);

    String getCity();

    void setCity(String value);

    String getCountryId();

    void setCountryId(String value);

    String getCreatedBy1();

    void setCreatedBy1(String value);

    Date getCreationDate1();

    void setCreationDate1(Date value);

    Date getLastUpdateDate1();

    void setLastUpdateDate1(Date value);

    String getLastUpdatedBy1();

    void setLastUpdatedBy1(String value);

    Number getLatitude();

    void setLatitude(Number value);

    Number getLongitude();

    void setLongitude(Number value);

    Number getObjectVersionId1();

    void setObjectVersionId1(Number value);

    String getPostalCode();

    void setPostalCode(String value);

    String getStateProvince();

    void setStateProvince(String value);

    String getCountryName();

    void setCountryName(String value);

    String getCreatedBy2();

    void setCreatedBy2(String value);

    Date getCreationDate2();

    void setCreationDate2(Date value);

    String getIsoCountryCode();

    void setIsoCountryCode(String value);

    String getLanguage();

    void setLanguage(String value);

    Date getLastUpdateDate2();

    void setLastUpdateDate2(Date value);

    String getLastUpdatedBy2();

    void setLastUpdatedBy2(String value);

    Number getObjectVersionId2();

    void setObjectVersionId2(Number value);

    String getSourceLang();

    void setSourceLang(String value);

    String getCreatedBy3();

    void setCreatedBy3(String value);

    Date getCreationDate3();

    void setCreationDate3(Date value);

    String getDescription();

    void setDescription(String value);

    String getLanguage1();

    void setLanguage1(String value);

    Date getLastUpdateDate3();

    void setLastUpdateDate3(Date value);

    String getLastUpdatedBy3();

    void setLastUpdatedBy3(String value);

    String getLookupCode();

    void setLookupCode(String value);

    String getLookupType();

    void setLookupType(String value);

    String getMeaning();

    void setMeaning(String value);

    Number getObjectVersionId3();

    void setObjectVersionId3(Number value);

    String getSourceLang1();

    void setSourceLang1(String value);

    String getAddressLabel();

    void setAddressLabel(String value);
}
