package model.mwgl.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 05 06:31:11 IST 2022
// ---------------------------------------------------------------------
public interface OrdersVO extends ViewObject {
    void cancelOrdered();
}
