package model.mwgl.eo;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 30 05:59:34 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AddressesEODefImpl extends EntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AddressesEODefImpl() {
    }
}
