package model.mwgl.eo;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Oct 22 06:44:26 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OrderItemsEOCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public OrderItemsEOCollImpl() {
    }
}
