package model.mwgl.service.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.JboException;
import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 01 00:21:32 IST 2022
// ---------------------------------------------------------------------
public interface FodAppModule extends ApplicationModule {
    void removeItemFromCart(Number productId) throws JboException;

    void removeAllItemsFromCart();

    Row getProductIdViewCriteria(Number productID);

    void createOrderItems(Number productID);

    String createNewOrder();

    String addItemInTransientVO(Number productID) throws JboException;

    void userRegistrationCreateAddress();

    void userRegistrationCreate();
}
