package model.mwgl.service.client;

import model.mwgl.service.common.FodAppModule;

import oracle.jbo.Row;
import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 01 00:21:32 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FodAppModuleClient extends ApplicationModuleImpl implements FodAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public FodAppModuleClient() {
    }


    public void removeItemFromCart(Number productId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"removeItemFromCart",new String [] {"oracle.jbo.domain.Number"},new Object[] {productId});
        return;
    }

    public void removeAllItemsFromCart() {
        Object _ret =
            this.riInvokeExportedMethod(this,"removeAllItemsFromCart",null,null);
        return;
    }

    public Row getProductIdViewCriteria(Number productID) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getProductIdViewCriteria",new String [] {"oracle.jbo.domain.Number"},new Object[] {productID});
        return (Row)_ret;
    }

    public void createOrderItems(Number productID) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createOrderItems",new String [] {"oracle.jbo.domain.Number"},new Object[] {productID});
        return;
    }

    public String createNewOrder() {
        Object _ret = this.riInvokeExportedMethod(this,"createNewOrder",null,null);
        return (String)_ret;
    }

    public String addItemInTransientVO(Number productID) {
        Object _ret =
            this.riInvokeExportedMethod(this,"addItemInTransientVO",new String [] {"oracle.jbo.domain.Number"},new Object[] {productID});
        return (String)_ret;
    }

    public void userRegistrationCreateAddress() {
        Object _ret =
            this.riInvokeExportedMethod(this,"userRegistrationCreateAddress",null,null);
        return;
    }

    public void userRegistrationCreate() {
        Object _ret =
            this.riInvokeExportedMethod(this,"userRegistrationCreate",null,null);
        return;
    }
}
